### ISSUE TITLE
Support for ENV{NO_COLOR}

### ISSUE THREAD

**Issue by telatin** [rra/ansicolor#3]
I love this module, thanks for maintaining it.

It would be neat if Term::ANSIColor could check for `$ENV{NO_COLOR}` and disable any color output even if requested by the script in case NO_COLOR is set.

See: https://no-color.org/

In this way all tools using Term::ANSIColor would become NO_COLOR compliant.

Thanks!

**Comment by rra** [comment]
Thanks for the pointer! I've now implemented this for the next release. It should be working on the master branch.

**Comment by telatin** [comment]
Thank you very much! This was insanely fast!
I was updating the unit tests and the POD, sorry for the initial PR that was unfinished :)

Best wishes

**Comment by rra** [comment]
Happy to help, and sorry, probably should have waited for you to finish your diff! I thought "oh, this would probably be easy" and then ran into all the test framework weirdness that you probably ran into, but by that point I was too much in the middle of things.

**Comment by telatin** [comment]
devel::cover is the beast, right? I admit i was stuck there

**Comment by rra** [comment]
Yeah, its interaction with `AUTOLOAD` is really weird. I had to rediscover the workaround that I had in place. Every `AUTOLOAD`-generated sub is treated as separate code for coverage purposes, so every branch in every generated sub has to be exercised.

This is partly my fault for reaching 100% coverage, which I normally don't do since it normally isn't worth the hassle.
